global:
  scrape_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
      - targets: ['172.18.37.105:9100']
      - targets: ['172.18.34.113:9100']
      - targets: ['172.18.36.187:9100']
  - job_name: 'cadvisor-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor-exporter:8080']
      - targets: ['172.18.37.105:9200']
      - targets: ['172.18.34.113:9200']
      - targets: ['172.18.36.187:9200']
